FizzBuzzTestApp/Models/FizzBuzzModel.cs
// <copyright file="FizzBuzzModel.cs" company="CompanyName">
//  Company copyright tag.
// </copyright>
//// Model contains a property to store the results
namespace FizzBuzzTestApp.Models
{
    using System.Collections.Generic;
    
    /// <summary>
    /// This class contains a property for the user inputted number
    /// </summary>
    public class FizzBuzzModel
    {
        /// <summary>
        /// Gets and sets property is used to store the results.
        /// </summary>
        public List<string> LstNumbers { get; set; }
    }
}

FizzBuzzTestApp/Controllers/FizzBuzzController.cs
// <copyright file="FizzBuzzController.cs" company="CompanyName">
//  Company copyright tag.
// </copyright>
//// This controller Class contains a logic to call the Business layer
//// The first request will come to this controller 
namespace FizzBuzzTestApp.Controllers
{
    using System;
    using System.Web.Mvc;
    using BusinessLayer.Interfaces;
    using Models;

    /// <summary>
    /// This Class contains a logic to call the Business layer
    /// </summary>
    public class FizzBuzzController : Controller
    {
        /// <summary>
        /// Read only property for interface helps in constructor injection
        /// </summary>
        private readonly IGetFizzBuzzPattern igetFizzBuzzPattern;

        /// <summary>
        /// Constructor Injection
        /// </summary>
        /// <param name="getFizzBuzzPattern">getFizzBuzzPattern</param>
        public FizzBuzzController(IGetFizzBuzzPattern getFizzBuzzPattern)
        {
            this.igetFizzBuzzPattern = getFizzBuzzPattern;
        }

        /// <summary>
        /// This method accepts input number as parameter
        /// </summary>
        /// <param name="number">user input number</param>
        /// <returns>view with list of numbers</returns>
        [HttpGet]
        public ActionResult UserInput(string number)
        {
            var model = new FizzBuzzModel();
            var result = this.igetFizzBuzzPattern.GetFizzBuzzPatterns(Convert.ToInt32(number));
            model.LstNumbers = result;
            return View(model);
        }
    }
}

FizzBuzzTestApp/Views/FizzBuzz/UserInput.cshtml
@model FizzBuzzTestApp.Models.FizzBuzzModel

@{
    ViewBag.Title = "Fizz Buzz Application";
}

<script src="~/Scripts/jquery-1.4.4.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/FizzBuzzValidation.js"></script>
<title>Fizz Buzz Application</title>
<h3 style="color: Blue">Fizz Buzz Application</h3>
<script type="text/javascript">
    $(document).ready(function () {
        $('#btnGet').click(function () {
            var value = $("#txtNumber").val();

            if (value === "") {
                alert('Input cannot be empty!');
                $("#txtNumber").focus();
                return false;
            }
            if (value === "0") {
                alert('Input cannot be zero.Please input a number greater than zero!');
                $("#txtNumber").val("");
                $("#txtNumber").focus();
                return false;
            }
            if (value > 1000) {
                alert('Enter an range between 0 and 1000');
                $("#txtNumber").focus();
                $("#txtNumber").val("");
                return false;
            }
            var url = '@Url.Action("UserInput", "FizzBuzz", new { })' + '?Number=' + $("#txtNumber").val();
            window.location.href = url;
            return false;
        });
    });

    $(document).ready(function () {
        $('tr').each(function () {
            if ($(this).children("td:nth-child(1)").text() === "fizz")
                $(this).children("td:nth-child(1)").css("color", "rgb(39, 0, 255)");
            else if ($(this).children("td:nth-child(1)").text() === "buzz") {
                $(this).children("td:nth-child(1)").css("color", "#058000");
            }
        });
    });

</script>
@using (Html.BeginForm())
{
    <form id="frmFizzBuzz">
        <table>
            <tr>
                <td>
                    @Html.Label("Please enter an integer:")
                </td>
                <td>
                    <input type="text" id="txtNumber" name="txtNumber" title="Please Enter an Integer" />
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="button" id="btnGet" value="GetNumbers" style="color: white; background-color: cadetblue" />
                </td>
            </tr>
            <tr>
                <td>
                    @{
    var grid = new WebGrid(Model.LstNumbers, canPage: true, rowsPerPage: 20,
        selectionFieldName: "selectedRow", ajaxUpdateContainerId: "gridContent");
                        @grid.Pager(WebGridPagerModes.FirstLast)
                    }


                    @grid.GetHtml(
                        htmlAttributes: new { id = "gridNum" },
                        tableStyle: "webGrid",
                        headerStyle: "header",
                        alternatingRowStyle: "alt",
                        selectedRowStyle: "select",
                        previousText: "<Prev",
                        nextText: "Next>",
                        columns: grid.Columns(
                            grid.Column(format: item => item, header: "Result:")
                            ))
                </td>
            </tr>
        </table>
        <br />
        <br />
    </form> 
}